"""edit name field

Revision ID: 168fa6a1a1a7
Revises: 87bcbad5ec5f
Create Date: 2023-03-23 19:27:27.243310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '168fa6a1a1a7'
down_revision = '87bcbad5ec5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('username', sa.String(), nullable=True))
    op.drop_constraint('admin_user_loging_key', 'admin_user', type_='unique')
    op.create_unique_constraint(None, 'admin_user', ['username'])
    op.drop_column('admin_user', 'loging')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('loging', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admin_user', type_='unique')
    op.create_unique_constraint('admin_user_loging_key', 'admin_user', ['loging'])
    op.drop_column('admin_user', 'username')
    # ### end Alembic commands ###
