"""add field password

Revision ID: 4befb9120f75
Revises: 07df2080b7c5
Create Date: 2023-04-07 00:48:55.556906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4befb9120f75'
down_revision = '07df2080b7c5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('password', postgresql.BYTEA(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'password')
    # ### end Alembic commands ###
