"""delete column

Revision ID: 58941bad64c0
Revises: d9f8fc3fff8c
Create Date: 2023-03-21 23:00:58.882525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58941bad64c0'
down_revision = 'd9f8fc3fff8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'date_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('date_time', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
