"""edit column

Revision ID: 5f7802aa0b8d
Revises: d9f8fc3fff8c
Create Date: 2023-03-14 20:06:16.460264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5f7802aa0b8d'
down_revision = 'd9f8fc3fff8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('desserts', 'image_url',
               existing_type=sa.VARCHAR(),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('desserts', 'image_url',
               existing_type=postgresql.BYTEA(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
