"""delete table to flask_login_1

Revision ID: 674057b8fa15
Revises: 2f730f04fcb1
Create Date: 2023-06-01 00:14:15.798419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '674057b8fa15'
down_revision = '2f730f04fcb1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.drop_table('roles_users')
    op.drop_table('admin_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('admin_user_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_user_pkey'),
    sa.UniqueConstraint('email', name='admin_user_email_key'),
    sa.UniqueConstraint('login', name='admin_user_login_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name='roles_users_role_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['admin_user.id'], name='roles_users_user_id_fkey')
    )
    op.drop_table('roles')
    # ### end Alembic commands ###
