"""add field active

Revision ID: 780129ba88f1
Revises: 4befb9120f75
Create Date: 2023-04-12 18:43:31.389290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '780129ba88f1'
down_revision = '4befb9120f75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'active')
    # ### end Alembic commands ###
