"""delete password

Revision ID: 855702d3dd4e
Revises: ec5f20290c9c
Create Date: 2023-03-29 18:46:34.820388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855702d3dd4e'
down_revision = 'ec5f20290c9c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('admin_user_password_key', 'admin_user', type_='unique')
    op.drop_column('admin_user', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('admin_user_password_key', 'admin_user', ['password'])
    # ### end Alembic commands ###
