"""edit password type filed

Revision ID: 9260b79b4eae
Revises: 855702d3dd4e
Create Date: 2023-03-29 18:46:50.076309

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9260b79b4eae'
down_revision = '855702d3dd4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('password', postgresql.BYTEA(), nullable=True))
    op.create_unique_constraint(None, 'admin_user', ['password'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_user', 'password')
    # ### end Alembic commands ###
