"""add column date time in order

Revision ID: 9ac9468618c8
Revises: 5f9ab65e0e4c
Create Date: 2023-03-21 23:11:22.643399

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9ac9468618c8'
down_revision = '5f9ab65e0e4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_time', postgresql.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.drop_column('orders', 'time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('time', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'date_time')
    # ### end Alembic commands ###
