"""add_new_models

Revision ID: d9f8fc3fff8c
Revises: fb70ea934efc
Create Date: 2023-03-01 19:15:03.482326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd9f8fc3fff8c'
down_revision = 'fb70ea934efc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('comment_id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.Column('comment', sa.TEXT(), nullable=True),
    sa.Column('date_time', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.order_id'], ),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.drop_column('orders', 'comment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('comment', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('comments')
    # ### end Alembic commands ###
