"""add column login

Revision ID: dd2ec8b82c7c
Revises: e1c9d4a10960
Create Date: 2023-04-26 18:38:14.204821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd2ec8b82c7c'
down_revision = 'e1c9d4a10960'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('login', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'admin_user', ['login'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_user', type_='unique')
    op.drop_column('admin_user', 'login')
    # ### end Alembic commands ###
