"""edit tables to security

Revision ID: e1c9d4a10960
Revises: 81528d98be56
Create Date: 2023-04-26 14:47:35.181212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c9d4a10960'
down_revision = '81528d98be56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('email', sa.String(), nullable=True))
    op.add_column('admin_user', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_constraint('admin_user_username_key', 'admin_user', type_='unique')
    op.create_unique_constraint(None, 'admin_user', ['email'])
    op.drop_column('admin_user', 'first_name')
    op.drop_column('admin_user', 'username')
    op.drop_column('admin_user', 'last_name')
    op.add_column('role', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role', 'description')
    op.add_column('admin_user', sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin_user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('admin_user', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'admin_user', type_='unique')
    op.create_unique_constraint('admin_user_username_key', 'admin_user', ['username'])
    op.drop_column('admin_user', 'active')
    op.drop_column('admin_user', 'email')
    # ### end Alembic commands ###
