"""add new field to adminuser

Revision ID: ec5f20290c9c
Revises: 168fa6a1a1a7
Create Date: 2023-03-29 18:29:33.157069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec5f20290c9c'
down_revision = '168fa6a1a1a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin_user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('admin_user', sa.Column('second_name', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'admin_user', ['second_name'])
    op.create_unique_constraint(None, 'admin_user', ['first_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'admin_user', type_='unique')
    op.drop_constraint(None, 'admin_user', type_='unique')
    op.drop_column('admin_user', 'second_name')
    op.drop_column('admin_user', 'first_name')
    # ### end Alembic commands ###
